### ISSUE TITLE
logger usage in `rsyncd` package

### ISSUE THREAD

**Issue by bcho** [gokrazy/rsync#19]
Hey, thanks for creating this great package! I am trying to import the `rsyncd` package in one of my project. I am trying to create the rsyncd server directly. However, seems like the rsyncd server is using the builtin logger package:

https://github.com/gokrazy/rsync/blob/de1cff573bd22217f6d5669b89a70f84c3a51829/rsyncd/rsyncd.go#L9

And it's calling fatal during the execution:

https://github.com/gokrazy/rsync/blob/c271006f2d3fa756367a856165d349862ae44aa6/rsyncd/filoio.go#L104-L105

Is that possible to:

1. define a logger interface to be used inside the server
2. expose the error handle in above code (I didn't have time to go through the code, but I think we should be able to fix it to avoid panic)

**Comment by stapelberg** [comment]
Yeah, in general we should try to eliminate any log.Fatal calls.

The one you link to can be removed once the TODO is addressed.

I don’t think we need to introduce an interface, instead we can remove the calls.

**Comment by bcho** [comment]
Thanks for your reply! In my project, I want to replace the logger to adjust the logging behavior. Without using a logger interface, how can we archive that?

**Comment by stapelberg** [comment]
Oh, I think I read your 2 questions as 1 question.

For log.Printf calls (which should remain), we can introduce an interface.

For log.Fatal calls, we should remove the calls.

**Comment by bcho** [comment]
I created a draft PR in #20, PTAL

**Comment by stapelberg** [comment]
This issue can be closed now since your PR #20 was merged, right? Or is there anything specific left to do?

**Comment by bcho** [comment]
Yeah let’s close it. I will open other prs if  further changes needed
