### ISSUE TITLE
build_hash_table seems not point to the first entry

### ISSUE THREAD

**Issue by guodoliu** [gokrazy/rsync#25]
// “A 16 bit index table is then formed which takes a 16 bit hash
// value and gives an index into the sorted signature table which
// points to the first entry in the table which has a matching
// hash.”
for idx := range head.Sums {
	tagTable[targets[idx].tag] = idx
}

here the latter will overwrite the previous value

**Comment by stapelberg** [comment]
Thanks for the hint. This is changed with commit https://github.com/gokrazy/rsync/commit/197246cdaa697ce55d511dd99491a2cc1465ef18 now.

Newer versions of rsync seem to use a dynamically allocated hash table with 32 bit keys.
