### ISSUE TITLE
Build fromm scratch

### ISSUE THREAD

**Issue by Eckert-IT** [gokrazy/rsync#26]
I like to use this package offline for different Workstation.
How do I build this from scratch (like make) ?

**Comment by stapelberg** [comment]
Please see the documentation on https://go.dev, for example the tutorial, and in particular https://go.dev/doc/tutorial/compile-install

From the `rsync` git checkout directory, use `go install github.com/gokrazy/rsync/cmd/...` to compile and install all commands.

**Comment by Eckert-IT** [comment]
Thank you for your gently answer. I'm pretty new to this topic.

Do you think that it should be possible to build this for a windows environment?

**Comment by stapelberg** [comment]
Our GitHub Actions CI already verifies that gokrazy/rsync always builds for Linux, macOS and Windows, so yes.

**Comment by Eckert-IT** [comment]
Thank you very much.

**Comment by Eckert-IT** [comment]
Thank you again for your work. I was able to run the program within an Windows-Environment with 

```
go install github.com/gokrazy/rsync/cmd/gokr-rsyncd@latest
gokr-rsyncd --daemon --gokr.listen=localhost:8730 --gokr.modulemap=pwd=$PWD
```

But I can't build the project to an executeable file like:
`go build -o gokr-rsyncd.exe github.com/gokrazy/rsync/rsyncd`


I tried twice: on a Windows machine an on a Raspberry Pi. The error message (on a Windows machine) is always the same, that the output is a "unsupported 16 bit application" (Windows Event ID 1109, http://deusexmachina.uk/evdoco/event.php?event=937).

Enviroment variables see to be Ok:
```
GOARCH=amd64
GOHOSTARCH=amd64
GOHOSTOS=windows
GOOS=windows
```

I tried to look it up like this:
https://stackoverflow.com/questions/26951762/i-cant-run-go-programs-anymore

But I can't find my mistake and would appreciate any help. Thank you.

**Comment by stapelberg** [comment]
> But I can't build the project to an executeable file like:
> `go build -o gokr-rsyncd.exe github.com/gokrazy/rsync/rsyncd`

You’re using the wrong import path. You wrote “github.com/gokrazy/rsync/rsyncd”, you should be using a path within cmd, e.g. “github.com/gokrazy/rsync/cmd/gokr-rsyncd”

**Comment by Eckert-IT** [comment]
Thank you again. I used the wrong Import path and didn't see it.
